Package splitting and documentation updates
juliendelplanque/JRPC pull request #19
Opened 2019-11-15 13:52 UTC by gcotelli

Fixes #15 
Fixes #16 
Fixes #17 
Fixes #18

@juliendelplanque please review the handlers documentation

2019-11-15 15:33 UTC, gcotelli commented
@juliendelplanque I think the PR is ready for review. I don't get why the coverage decreased given I've just moved code from one package to other packages. Maybe it depends on the way Coveralls combines the coverage info from different packages?

2019-11-16 13:07 UTC, juliendelplanque requested changes

2019-11-16 13:07 UTC, juliendelplanque commented on docs/MessageProcessing.md
> +The message processor has available a list of method handlers that will be searched when a incoming message is received, if a suitable handler is found then it gets executed with the parameters provi
```suggestion
The message processor has a list of method handlers available that will be searched when a incoming message is received. If a suitable handler is found (the `#methodName` is matching) then it gets executed with the parameters provided in the message.
```

2019-11-16 13:07 UTC, juliendelplanque commented on docs/MessageProcessing.md
> +To configure a message processor use any of the following messages to add new handlers:
```suggestion
A message processor can be configured using the following messages:
```

2019-11-16 13:07 UTC, juliendelplanque commented on docs/MessageProcessing.md
> +- `addHandlerNamed:block:` will add a new handler for a method that will evaluate the provided block
```suggestion
- `addHandlerNamed:block:`adds a new handler for a method that will evaluate the block provided as argument.
```

2019-11-16 13:07 UTC, juliendelplanque commented on docs/MessageProcessing.md
> +- `addHandlersFromPragmasIn:` will search for `<jrpc>` pragmas declared in the methods of the parameter object, and will add a message handler if found.
```suggestion
- `addHandlersFromPragmasIn:` searches for `<jrpc>` pragmas declared in the methods of the object provided as argument, and adds a message handler if such pragma is found. When such handler is added, the method in which the pragma was found is sent to the object when a matching JRPC message is received.
```

2019-11-16 13:07 UTC, juliendelplanque commented on docs/MessageProcessing.md
> +- `addHandler:` will add a new handler. Handlers must subclass `JRPCAbstractHandler`, this allows the end user to extend the available options if needed.
```suggestion
- `addHandler:` adds a new handler. Handlers must subclass `JRPCAbstractHandler`, this allows the end user to extend the available options if needed.
```

2019-11-16 13:07 UTC, juliendelplanque commented on docs/MessageProcessing.md
> +The message processor main API is `handleJSON:` , any server implementing an specific transport protocol must obtain the json string and delegate it's processing by sending this message and will rece
```suggestion
The message processor main API is `handleJSON:`, any server implementing a specific transport protocol must obtain the json string and delegate its processing by sending `handleJSON:` to the processor. `handleJSON:` method returns the JSON string to return to the client once the processing is completed.
```

2019-11-16 13:07 UTC, juliendelplanque commented on docs/MessageProcessing.md
> +Message handlers are responsible of executing the code related to a method. All handlers are subclasses of `JRPCAbstractHandler` and need to provide a `methodName` and a way to execute this method wi
```suggestion
Message handlers are responsible of executing the code related to a JRPC method. All handlers are subclasses of `JRPCAbstractHandler` and need to provide a `methodName` and a way to execute this method with the provided arguments. There's two implementations already available `JRPCBlockHandler` and `JRPCPragmaHandler`.
```

2019-11-16 13:07 UTC, juliendelplanque commented on docs/MessageProcessing.md
> +- `JRPCBlockHandler` instances are created with a block closure that will we evaluated to compute the method. The parameter names are taken from the block.
```suggestion
- `JRPCBlockHandler` instances are created with a block closure that will be evaluated to compute the method. The parameter names are taken from the block parameters names.
```

2019-11-16 13:23 UTC, gcotelli commented
Applied code review suggestions

2019-11-16 13:45 UTC, juliendelplanque approved these changes

2019-11-16 13:45 UTC, merged